### ISSUE TITLE
执行 ./capture-image-from-camera-using-opencv.sh报错

### ISSUE THREAD

**Issue by lmule** [codelast/raspberry-pi#1]
hi你好，我在执行 ./capture-image-from-camera-using-opencv.sh这个脚本的时候报错：
Compiling /home/pi/workspace/camera/raspberry-pi/webcam/image-capture/opencv/webcam.c ...
In file included from /usr/include/opencv2/opencv.hpp:59:0,
                 from /home/pi/workspace/camera/raspberry-pi/webcam/image-capture/opencv/webcam.c:3:
/usr/include/opencv2/contrib/contrib.hpp:56:1: error: ‘use’ does not name a type
In file included from /usr/include/opencv2/opencv.hpp:59:0,
                 from /home/pi/workspace/camera/raspberry-pi/webcam/image-capture/opencv/webcam.c:3:
/usr/include/opencv2/contrib/contrib.hpp:276:39: error: ‘vector’ does not name a type
/usr/include/opencv2/contrib/contrib.hpp:276:45: error: expected ‘,’ or ‘...’ before ‘<’ token
/usr/include/opencv2/contrib/contrib.hpp: In member function ‘const Point3f& cv::SpinImageModel::getSpinVertex(size_t) const’:
/usr/include/opencv2/contrib/contrib.hpp:347:72: error: ‘const class cv::Mesh3D’ has no member named ‘vtx’
请问这个是什么问题呢
我的树莓派版本是B+，sudo apt-get install libopencv-dev python-opencv使用这种方式安装的opencv

**Comment by codelast** [comment]
看样子你用的是Raspbian系统？
我是在Arch Linux ARM系统上测试的代码，没有测试过Raspbian。
怀疑是系统中缺少什么包没装的问题（不确定）。
可以参考一下：http://milq.github.io/install-opencv-ubuntu-debian/
